version: '3'

services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile.${DOCKER_ENV}
    volumes:
      - test-coverage-report-volume:/var/html/test-coverage-report
    ports:
      - "80:80"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      backend:
        aliases:
          - techtest.backend

  php-fpm:
    build:
      context: ..
      dockerfile: docker/php-fpm/Dockerfile.${DOCKER_ENV}
    volumes:
      - test-coverage-report-volume:/var/html/test-coverage-report
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    stdin_open: true
    tty: true
    networks:
      - backend

  mariadb:
    build:
      context: ..
      dockerfile: docker/mariadb/Dockerfile.${DOCKER_ENV}
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    stdin_open: true
    tty: true
    networks:
      backend:
        aliases:
          - database.backend

networks:
  backend:
    driver: "bridge"

volumes:
  test-coverage-report-volume: