version: '3'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../public:/usr/share/nginx/html
      - ../log:/var/log
    ports:
      - "80:80"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      backend:
        aliases:
          - techtest.backend

  php-fpm:
    build:
      context: ./php-fpm
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../public:/usr/share/techTest/public
      - ../src:/usr/share/techTest/src
      - ../test:/usr/share/techTest/test
      - ./php-fpm/root_home:/root
    stdin_open: true
    tty: true
    networks:
      - backend

  mariadb:
    build:
      context: ./mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
    stdin_open: true
    tty: true
    networks:
      backend:
        aliases:
          - database.backend

networks:
  backend:
    driver: "bridge"
