FROM nginx:alpine
WORKDIR /usr/share/nginx/
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/sites/ /etc/nginx/sites-available/
COPY ./docker/nginx/conf.d/ /etc/nginx/conf.d/
COPY ./public/ /usr/share/nginx/html/
CMD ["nginx"]
EXPOSE 80
